### ISSUE TITLE
How to remove 's' from folder titles?

### ISSUE THREAD

**Issue by stopusingthisplatformplease** [victoriadrake/hugo-theme-quint#3]
By default posts gets put in content/blog and when I visit http://localhost:1313/blog the title of the page is Blogs.

However, after copying over and changing `layouts/index.html` to for instance texter instead of blog for instance `{{ $posts := where .Site.RegularPages "Section" "texter" }}` (and renaming content/blog to content/texter) now the title in localhost:1313/texter is Texters.

How do I get rid of the extra s?

**Comment by victoriadrake** [comment]
Hello!

In your `content/texter/` directory, make sure you have an `_index.md` file with frontmatter that defines the title for the section. For example:

```md
---
title: "Texter"
menus: "main"
---
```

This allows you to customize the title for the page.
