### ISSUE TITLE
social icons have bad color when in dark mode

### ISSUE THREAD

**Issue by ganomi46** [victoriadrake/hugo-theme-quint#5]
**Describe the bug**
When in dark mode, social icons have black color which makes them invisible

**To Reproduce**
1. Set dark mode in the browser
2. reload page
3. social icons are black on dark background

**Expected behavior**
Social icons should change contrast to white

**Screenshots**
![image](https://github.com/user-attachments/assets/312728c0-2083-4d8a-83e8-bf10fb9eae59)

**Desktop (please complete the following information):**
 - Tumbleweed

**Smartphone (please complete the following information):**
- same on all devices
 
**Additional context**
I also think the icons have bad position. It would be better to push them in the middle under the title/subtitle.

**Comment by victoriadrake** [comment]
Thank you for opening this issue!

If you'd like to change the position of the icons, you can edit or override the `site_root/themes/quint/layouts/partials/footer.html` file. To override it, copy it into your `site_root/layouts/partials/` directory and make changes as you like.

**Comment by ganomi46** [comment]
> Describe the bug
> When in dark mode, social icons have black color which makes them invisible

@victoriadrake so I did you address the colors in your response above?
