### ISSUE TITLE
image banner not displayed on the page when manually specified

### ISSUE THREAD

**Issue by ganomi46** [victoriadrake/hugo-theme-quint#6]
**Describe the bug**
Image banner not displayed on the page when manually specified.

**To Reproduce**
1. Add image to a post with "image: images/image.jpg 
2. The image is displayed on the home page grid, but not on the page itself

**Expected behavior**
the image is displayed as banner on the page (behind the title)

**Desktop (please complete the following information):**
 - tumbleweed

**Smartphone (please complete the following information):**
 - all devices

**Additional context**
When I use the auto-rotation the image is displayed on the home page grid and also on the page itself.

**Comment by victoriadrake** [comment]
Where is `image.jpg` stored? If it is in `siteroot/static/images/image.jpg` then you may need to add the leading slash in your front matter:

```
image: /images/image.jpg
```

Without the leading `/`, the template is looking for an `images` folder in the same directory as your post.

**Comment by ganomi46** [comment]
You are correct. Thank you.
